# Booking.com Feature Extraction
---

Download the file BookingDotCom_HotelReviews.xlsx from Canvas. This file contains over 515,000 guest reviews and rating of almost 1500 hotels across Europe scraped from popular hotel reservation website Booking.com. The text data was cleaned by removing unicode and punctuation and transformed to lower case. No other preprocessing was done. More information on each field is provided in the "Data Description" tab of the Excel file.

        1. What are the top five hotel features (e.g., location, staff, etc.) that customers mention the most in positive reviews and top five features they mention most in negative reviews? Your identified features must make sense (e.g., "great" or "negative" are not features). (3 points)
        
        2. What are the top five features that customers prefer most if they are a solo traveler vs traveling with a group vs on a business trip vs a leisure trip vs traveling as a couple vs a family with young children. You will find these categories in the "Tags" column. There are a few more tags that we don't need. (2 points).

        3. What are the top five features customers like most and top five features they complain about most about hotels in United Kingdom, France, Italy, and Spain? Country information is available inside Hotel_Address. (2 points)
        
        4. Create a dashboard with the following plots; (1) "Top Five Hotels Overall" with consistently high ratings, (2) Bottom Five Hotels Overall" with consistently low ratings, (3) Five Most Improved Hotels" with the highest improvement in average ratings from 2015 to 2017, showing their average ratings for each of the three years. (0.5+0.5+2 points).

Write clear, compact, and understandable code with comment/markdown statements as appropriate. Non-working code or unnecessary code will be penalized. 

Submit your Jupyter file using the link below or provide a link to your Google Colab or Github file.


In [1]:
# import packages to use
import pandas as pd
import pycountry
import spacy
from spacy import displacy
# from collections import Counter
import en_core_web_sm

In [ ]:
'''
# load dataframe
df = pd.read_excel("BookingDotCom_HotelReviews.xlsx", sheet_name="Data")

# sample the first 100 rows of df
df = df[:100]

# rename df columns to lower case
df.columns= df.columns.str.lower()
'''

In [2]:
df = pd.read_csv("bookingdotcom.csv")

In [3]:
# convert to lowercase & remove double/unneccessary spaces between words in columns of comments
df['positive_comments'] = df['positive_comments'].str.lower().apply(lambda x: " ".join(x.split()))
df['negative_comments'] = df['negative_comments'].str.lower().apply(lambda x: " ".join(x.split()))

In [4]:
# remove stopwords

from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

df['positive_comments'] = df['positive_comments'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop_words)]))
df['negative_comments'] = df['negative_comments'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop_words)]))

In [5]:
# drop numbers from string

df['positive_comments'] = df['positive_comments'].str.replace('\d+', '')
df['negative_comments'] = df['negative_comments'].str.replace('\d+', '')

C:\Users\echemochek\AppData\Local\Temp\ipykernel_16728\3288369858.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df['positive_comments'] = df['positive_comments'].str.replace('\d+', '')
C:\Users\echemochek\AppData\Local\Temp\ipykernel_16728\3288369858.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df['negative_comments'] = df['negative_comments'].str.replace('\d+', '')


In [6]:
'''
Create column with country name; we get the list of countries from the pycountry package
and use the hotel_address column to extract country name
'''

df['country'] = df["hotel_address"].apply(
    lambda address: ' '.join([c.name for c in pycountry.countries if c.name in address])
    )

# use the review_date column to extract the year and store in new column
df['year'] = pd.DatetimeIndex(df['review_date']).year

In [7]:
'''
In this step we deal with the tags column using the steps defined below:
    1. Define tags we are interested in
    2. Define a function to apply to tags column to remove tags we are not interested in by:
            - Converting the individual row values to list (from string) e.g. "[' Leisure trip ']" -> [' leisure trip ']
            - Strip the whitespaces from individual elements e.g. [' leisure trip ']-> ['leisure trip']
            - Drop tags we are not interested in
'''

# customer tags we are interested in
customer_tags = [
    'solo traveler',
    'group',
    'business trip',
    'leisure trip',
    'couple',
    'family with young children'
]

def clean_tag(x):

    # convert value from string to a list
    import ast
    
    myTags = ast.literal_eval(x.lower())

    # strip whitespaces from elements and drop those we are not interested in
    myTags = [customerTag.strip() for customerTag in myTags if customerTag.strip() in customer_tags]

    return myTags


# apply clean_tag() function to the tags column
df['tags'] = df['tags'].apply(lambda x: clean_tag(x))

In [8]:
'''
Function applied to tags column to extract new columns for customer categories
Lambda function will be used as in the steps below
'''
def split_tag(x:list, tagName:str) -> int:
    
    t = [1 if tagName in x else 0][0]
    
    return t

# dictionary of column names (new additional columns) and customer tags (as contained in tags of interest)
tagDict = {
    'solo_traveler' : 'solo traveler',
    'group' : 'group',
    'business_trip' : 'business trip',
    'leisure_trip' : 'leisure trip',
    'couple' : 'couple',
    'family_with_young_children' : 'family with young children'
}

# applying function on tags column to get new separated columns
for key, value in tagDict.items():
    df[key] = df['tags'].apply(lambda x: split_tag(x, value))

In [9]:
# drop columns we do not need for now
colsToDrop = [
    'hotel_address', 
    'review_date', 
    'reviewer_nationality', 
    'tags'
    ]

df.drop(columns=colsToDrop, inplace=True)

1. Text Processing
- Cleaning
- Normalization
- Tokenization
- Removing stopwords
- POS tagging
- Named Entity Recognition
- Lemmatization

2. Feature Extraction
- Bag of Words
- TF-IDF
- Word embeddings

3. Modeling

# NER

In [10]:
overallTokens = []

In [11]:
# instantiate Spacy model for performing NER
nlp = en_core_web_sm.load()

# apply model to text
doc = nlp(df.positive_comments[10])
doc.text

'rooms stunningly decorated really spacious top building pictures room  true beauty building kept modernised brilliantly also bath lovely big inviting great couples restaurant menu bit pricey loads little eatery places nearby within walking distance tram stop centre  minute walk away   stops centre amsterdam would recommend hotel anyone unbelievably well priced'

In [ ]:
# docs = list(nlp.pipe(df.positive_comments))
# len(docs)

In [12]:
# entities
docEntities = list(doc.ents)
docEntities

overallTokens = overallTokens + docEntities

In [13]:
overallTokens

[]

In [14]:
'''
# !!! remove stopwords

# nounPhrases
nounPhrases = [chunk.text for chunk in doc.noun_chunks]
nounPhrases

overallTokens = overallTokens + nounPhrases
'''

'\n# !!! remove stopwords\n\n# nounPhrases\nnounPhrases = [chunk.text for chunk in doc.noun_chunks]\nnounPhrases\n\noverallTokens = overallTokens + nounPhrases\n'

In [15]:
# !!! lemmatize first

# using POS tagging

pos = [
    'PROPN',
    'NOUN',
    'VERB'
]

clean_doc = [token.lemma_ for token in doc if token.pos_ in pos]
print(clean_doc)

overallTokens = overallTokens + clean_doc

['room', 'decorate', 'building', 'picture', 'room', 'beauty', 'building', 'keep', 'modernise', 'bath', 'invite', 'couple', 'restaurant', 'menu', 'bit', 'load', 'eatery', 'place', 'walk', 'distance', 'tram', 'stop', 'centre', 'minute', 'walk', 'stop', 'centre', 'amsterdam', 'recommend', 'hotel', 'price']


In [ ]:
overallTokens

In [ ]:
'''
# sentences
spSent = list(doc.sents)

# words
spWords = [w.text for w in doc]

'''

In [45]:
# Word frequency
from collections import Counter

spCleanWordFreq = Counter(overallTokens)
print(spCleanWordFreq)

# counterSum = counter1 + counter2

Counter({'room': 2, 'building': 2, 'walk': 2, 'stop': 2, 'centre': 2, 'decorate': 1, 'picture': 1, 'beauty': 1, 'keep': 1, 'modernise': 1, 'bath': 1, 'invite': 1, 'couple': 1, 'restaurant': 1, 'menu': 1, 'bit': 1, 'load': 1, 'eatery': 1, 'place': 1, 'distance': 1, 'tram': 1, 'minute': 1, 'amsterdam': 1, 'recommend': 1, 'hotel': 1, 'price': 1})


In [46]:
type(spCleanWordFreq)

collections.Counter

In [51]:
x = spCleanWordFreq.most_common(5)


In [24]:
'''
# Words occurring twice or more
spFreqCleanWords = [w for (w, freq) in spCleanWordFreq.items() if freq > 1]
spFreqCleanWords
'''

['room', 'building', 'walk', 'stop', 'centre']

In [33]:
'''
# dependency parsing
sentence = doc
spSentence = nlp(sentence)

for w in spSentence:
     print (w.text, w.tag_, w.head.text, w.dep_)
'''

'\n# dependency parsing\nsentence = doc\nspSentence = nlp(sentence)\n\nfor w in spSentence:\n     print (w.text, w.tag_, w.head.text, w.dep_)\n'

In [32]:
'''
# shallow parsing
# noun phrase detection

for chunk in doc.noun_chunks:
     print (chunk)
'''

'\n# shallow parsing\n# noun phrase detection\n\nfor chunk in doc.noun_chunks:\n     print (chunk)\n'

# Coreference resolution
https://towardsdatascience.com/from-text-to-knowledge-the-information-extraction-pipeline-b65e7e30273e

# Bi-grams

https://medium.com/analytics-vidhya/feature-extraction-and-sentiment-analysis-of-reviews-of-3-apps-in-india-84b665e1a887

# Trial

In [ ]:
from nltk.tokenize import regexp_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
# !pip install gensim
from gensim.utils import simple_preprocess
from gensim.corpora import Dictionary

my_docs = ['This movie was about spaceships and aliens.',
           'I really enjoyed the movie!',
           'Awesome action scenes, but boring characters.',
           'The movie was awful! I hate alien films.',
           'Space is cool! I like space movies.',
           'More space films, please!']

tokens = [] # list of lists >> column of pos/neg reviews tokens

for doc in my_docs:
    words = regexp_tokenize(doc.lower(), r'[A-Za-z]+')
    words = [w for w in words if w not in stopwords.words('english')]
    words = [lemmatizer.lemmatize(w) for w in words]
    tokens.append(words)

my_dict = Dictionary(tokens) # dictionary
print(my_dict.token2id) 

# Note: You can also add new words or lists of words to a dictionary, save a
# dictionary to a file, load it back later, or read a dictionary from a text file

# my_dict.add_documents(list_of_new_words)
# my_dict.save('saved_dict.dict')
# loaded_dict = Dictionary.load('saved_dict.dict')
# dictionary = Dictionary(line.split()) for line in open('sample.txt', encoding='utf-8'))

dtm = [my_dict.doc2bow(doc) for doc in tokens]
dtm  # Create Gensim BOW corpus

for doc in dtm:
    print([[my_dict[i], freq] for i, freq in doc])

tokenList = tokens # list of lists

dtm = [my_dict.doc2bow(tokenListItem) for tokenListItem in tokenList]
dtm  # Create Gensim BOW corpus

In [53]:
from sklearn.feature_extraction.text  import CountVectorizer

In [58]:
vec = CountVectorizer(max_df=0.85, stop_words=stopwords.words('english'))
vec = CountVectorizer(max_df=0.85, max_features=5, stop_words='english')

dtm = vec.fit_transform(df['positive_comments'])   # You can fit and transform jointly 

In [59]:
print(dtm.toarray())

[[1 0 1 0 0]
 [1 1 0 0 2]
 [1 1 0 0 1]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [1 0 1 0 0]
 [1 0 1 1 0]
 [0 1 1 0 1]
 [0 0 0 0 0]
 [2 0 1 1 0]
 [1 0 0 1 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [2 1 1 1 0]
 [0 0 0 0 0]
 [2 0 1 2 1]
 [0 1 1 0 0]
 [2 1 1 0 1]
 [0 0 0 1 0]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [2 1 1 0 0]
 [1 1 1 0 0]
 [0 0 0 0 1]
 [3 1 0 3 1]
 [0 1 1 0 1]
 [4 1 1 2 1]
 [1 0 0 0 0]
 [1 0 1 0 0]
 [3 0 1 0 0]
 [0 0 1 0 1]
 [0 0 1 0 1]
 [0 0 0 0 0]
 [1 0 0 0 1]
 [0 1 1 1 0]
 [2 0 1 0 0]
 [0 0 1 1 0]
 [1 0 1 0 0]
 [0 1 0 1 1]
 [0 1 1 0 0]
 [1 0 1 0 1]
 [0 1 0 0 1]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [0 0 0 0 0]
 [1 1 0 1 1]
 [0 0 0 0 0]
 [1 1 0 1 0]
 [2 1 1 0 1]
 [0 0 0 0 0]
 [0 0 0 2 0]
 [0 1 0 0 0]
 [0 1 2 0 1]
 [0 0 2 1 0]
 [0 0 0 0 0]
 [1 0 1 0 1]
 [0 1 1 0 0]
 [1 1 1 2 1]
 [0 1 0 0 0]
 [3 1 0 1 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 3 2]
 [0 1 0 1 0]
 [2 0 1 0 0]
 [0 0 0 0 1]
 [0 0 0 3 1]
 [2 0 1 1 0]
 [0 0 0 1 1]
 [1 0 0 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 1 0]
 [0 0 0 0 0]
 [1 0 0 0 0]
 [2 0 0 1 1]
 [0 1 1 0 0]